#元组的概念和列表的应用差不多用（）
#但是元组的元素不可以改变但是里面如果有列表的话可以改变列表中的元素
#a=('hello','world',10,[1,2,3,])
#a[3][1]='heqimengzhenshuai'
#print(a)
#字符串，列表，元组得len(),max(),min()
#元组
a=(1,2,3,4)
print(len(a))
print(max(a))
print(min(a))
c=[1,2,3,4]
print(len(c))
print(max(c))
d='1,2,3,4,'
print(max(d))#用的是ascii浏览器查找
#元组的注意事项以及乘号的使用
e=(1,2,3,4,)
f=1,2,3
print(f)#元组可加逗号也可不加
#只有一个元组后面一定要加上逗号
f=1,
#元组的*
g=10,
print(g*10)